spin_duration_ms = 10000.0

[[segments]]
label = "1"
weight = 1

[[segments]]
label = "2"
weight = 1 

[[segments]]
label = "3"
weight = 1 

[[segments]]
label = "4"
weight = 1 

[[segments]]
label = "5"
weight = 1 

[[segments]]
label = "6"
weight = 1 

[[segments]]
label = "7"
weight = 1 

[[segments]]
label = "8"
weight = 1 

[[segments]]
label = "9"
weight = 1 

[[segments]]
label = "10"
weight = 1

[[segments]]
label = "11"
weight = 1

[[segments]]
label = "12"
weight = 1 

[[segments]]
label = "13"
weight = 1 

[[segments]]
label = "14"
weight = 1 

[[segments]]
label = "15"
weight = 1 

[[segments]]
label = "16"
weight = 1 

[[segments]]
label = "17"
weight = 1 

[[segments]]
label = "18"
weight = 1 

[[segments]]
label = "19"
weight = 1 

[[segments]]
label = "20"
weight = 1 





